# Generated by Django 3.0.7 on 2020-06-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short_id', models.SlugField()),
                ('is_valid', models.BooleanField(default=False)),
                ('redirect_count', models.IntegerField(default=0)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
