# Generated by Django 3.0.7 on 2020-06-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='is_valid',
            new_name='is_valida',
        ),
    ]
