# Generated by Django 3.0.7 on 2020-06-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0002_auto_20200604_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('file', models.FileField(blank=True, null=True, upload_to='urls/%Y/%m/%d', verbose_name='URLS')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['id'],
            },
        ),
    ]
