# Generated by Django 3.0.7 on 2020-06-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='fileid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shorturls.File', verbose_name='File'),
            preserve_default=False,
        ),
    ]
