# Generated by Django 3.0.7 on 2020-06-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0004_url_fileid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('short_id', models.SlugField()),
            ],
        ),
    ]
