# Generated by Django 3.0.7 on 2020-06-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0005_export'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Export',
        ),
    ]
